default_install_hook_types: [pre-commit, commit-msg]
exclude: ^(CHANGELOG.md)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.0.166
    hooks:
      - id: rumdl
        args: [--force-exclude, --fix]
  - repo: https://github.com/crate-ci/typos
    rev: v1.38.1
    hooks:
      - id: typos
        args: [--write-changes, --force-exclude, --config, .typos.toml]
  - repo: https://github.com/crate-ci/committed
    rev: v1.1.9
    hooks:
      - id: committed
        args: [--config, .committed.toml]
